### ISSUE TITLE
getting error 

### ISSUE THREAD

**Issue by engr-erum** [applm/CarouselWidget#3]
07-03 23:45:06.766: E/AndroidRuntime(970): FATAL EXCEPTION: main
07-03 23:45:06.766: E/AndroidRuntime(970): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.carouselapp/com.example.carouselapp.MainActivity}: android.view.InflateException: Binary XML file line #19: Error inflating class android.support.v7.internal.widget.NativeActionModeAwareLayout
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.app.ActivityThread.access$600(ActivityThread.java:130)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.os.Handler.dispatchMessage(Handler.java:99)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.os.Looper.loop(Looper.java:137)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.app.ActivityThread.main(ActivityThread.java:4745)
07-03 23:45:06.766: E/AndroidRuntime(970):  at java.lang.reflect.Method.invokeNative(Native Method)
07-03 23:45:06.766: E/AndroidRuntime(970):  at java.lang.reflect.Method.invoke(Method.java:511)
07-03 23:45:06.766: E/AndroidRuntime(970):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
07-03 23:45:06.766: E/AndroidRuntime(970):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
07-03 23:45:06.766: E/AndroidRuntime(970):  at dalvik.system.NativeStart.main(Native Method)
07-03 23:45:06.766: E/AndroidRuntime(970): Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class android.support.v7.internal.widget.NativeActionModeAwareLayout
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:698)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.view.LayoutInflater.parseInclude(LayoutInflater.java:805)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:299)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
07-03 23:45:06.766: E/AndroidRuntime(970):  at com.example.carouselapp.MainActivity.onCreate(MainActivity.java:23)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.app.Activity.performCreate(Activity.java:5008)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
07-03 23:45:06.766: E/AndroidRuntime(970):  ... 11 more
07-03 23:45:06.766: E/AndroidRuntime(970): Caused by: java.lang.ClassNotFoundException: android.support.v7.internal.widget.NativeActionModeAwareLayout
07-03 23:45:06.766: E/AndroidRuntime(970):  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
07-03 23:45:06.766: E/AndroidRuntime(970):  at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
07-03 23:45:06.766: E/AndroidRuntime(970):  at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.view.LayoutInflater.createView(LayoutInflater.java:552)
07-03 23:45:06.766: E/AndroidRuntime(970):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
07-03 23:45:06.766: E/AndroidRuntime(970):  ... 24 more
07-03 23:50:06.877: I/Process(970): Sending signal. PID: 970 SIG: 9

**Comment by tjbcg** [comment]
Same here.
Can't fix it... Why is this class not found since it's compiled ?

**Comment by Carlos2927** [comment]
I found how to fix it,see [https://code.google.com/p/android/issues/detail?id=180022](url),at 8 floor:
Had the same problem after updating to the most recent version of the support library. Check whether the following 'left-over' file exists: v7/appcompat/res/layout-v11/abc_screen_content_include.xml; if so delete it
